'use client'
import {useEffect,useRef,useState} from 'react'

type DeviceInfo={name:string,connected:boolean,service?:string}
const SERVICE='6e400001-0000-0000-006e-696e65626f74'
const WRITE='6e400002-0000-0000-006e-696e65626f74'
const NOTIFY='6e400004-0000-0000-006e-696e65626f74'

export default function Home(){
 const [device,setDevice]=useState<any>(null); const [info,setInfo]=useState<DeviceInfo|null>(null); const [log,setLog]=useState<string[]>([]); const [file,setFile]=useState<File|null>(null); const [progress,setProgress]=useState(0); const [busy,setBusy]=useState(false); const [tab,setTab]=useState('overview'); const [battery,setBattery]=useState('—'); const [speed,setSpeed]=useState('—'); const [fw,setFw]=useState('—'); const notifyRef=useRef<any>(null); const writeRef=useRef<any>(null)
 const add=(s:string)=>setLog(x=>[new Date().toLocaleTimeString()+'  '+s,...x].slice(0,30))
 async function connect(){
  if(!('bluetooth' in navigator)){add('Web Bluetooth wird von diesem Browser nicht unterstützt.');return}
  try{const d=await (navigator as any).bluetooth.requestDevice({acceptAllDevices:true,optionalServices:[SERVICE]});setDevice(d);setInfo({name:d.name||'Ninebot',connected:false});d.addEventListener('gattserverdisconnected',()=>{setInfo(v=>v?{...v,connected:false}:v);add('Bluetooth getrennt')});const s=await d.gatt.connect();setInfo({name:d.name||'Ninebot',connected:true,service:SERVICE});add('Verbunden: '+(d.name||'Ninebot'));let svc;try{svc=await s.getPrimaryService(SERVICE)}catch{add('Ninebot-Dienst nicht gefunden. Modell/Protokoll kann abweichen.');return}try{writeRef.current=await svc.getCharacteristic(WRITE)}catch{}try{notifyRef.current=await svc.getCharacteristic(NOTIFY);await notifyRef.current.startNotifications();notifyRef.current.addEventListener('characteristicvaluechanged',(e:any)=>{const v=new Uint8Array(e.target.value.buffer);add('BLE Notify: '+Array.from(v).map(x=>x.toString(16).padStart(2,'0')).join(' '))})}catch{}add('BLE-Kanal bereit')}
  catch(e:any){add('Verbindung abgebrochen/fehlgeschlagen: '+(e?.message||e))}
 }
 async function send(bytes:number[]){if(!writeRef.current)throw Error('Kein Schreibkanal');await writeRef.current.writeValue(new Uint8Array(bytes));}
 async function flash(){if(!file||!info?.connected){add('Verbinde den Scooter und wähle eine Firmware-Datei.');return}setBusy(true);setProgress(0);add('Firmware-Workflow gestartet.');add('Datei: '+file.name+' ('+file.size+' Bytes)');try{const b=new Uint8Array(await file.arrayBuffer());if(b.length<64){throw Error('Datei ist zu klein für eine gültige Firmware.')}add('Sicherheitsprüfung: Dateigröße OK.');add('WICHTIG: Modell-, Hardware- und Firmware-Kompatibilität muss vor dem Schreiben bestätigt werden.');add('Diese Web-App sendet keine unbekannte Firmware automatisch. Ein modellspezifischer DFU/IAP-Adapter ist erforderlich.');
 // Deliberately do not invent a flash protocol. Establishing the BLE transport is real; flashing requires a verified per-model bootloader implementation.
 setProgress(100);add('Transportprüfung abgeschlossen — Flash-Vorgang wurde aus Sicherheitsgründen nicht simuliert.');
 }catch(e:any){add('Fehler: '+(e?.message||e))}finally{setBusy(false)}}
 return <main><header><div><div className="brand">NINE<span>CONTROL</span></div><p>Bluetooth Utility für kompatible Ninebot Scooter</p></div><button className={info?.connected?'ok':''} onClick={connect}>{info?.connected?'● Verbunden':'Bluetooth verbinden'}</button></header>
 <section className="hero"><div><span className="pill">WEB BLUETOOTH</span><h1>Dein Scooter.<br/><i>Deine Kontrolle.</i></h1><p>Verbindung, Telemetrie und ein abgesicherter Firmware-Workflow in einer Oberfläche.</p></div><div className="device-card"><div className="dot"/><b>{info?.name||'Kein Scooter verbunden'}</b><small>{info?.connected?'GATT verbunden':'Warte auf Bluetooth-Verbindung'}</small></div></section>
 <nav>{[['overview','Übersicht'],['settings','Einstellungen'],['firmware','Firmware'],['logs','Protokoll']].map(([id,n])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{n}</button>)}</nav>
 {tab==='overview'&&<section className="grid"><Card title="Akku" value={battery} suffix="%"/><Card title="Geschwindigkeit" value={speed} suffix="km/h"/><Card title="Firmware" value={fw} suffix=""/><Card title="Verbindung" value={info?.connected?'ONLINE':'OFFLINE'} suffix=""/></section>}
 {tab==='settings'&&<section className="panel"><h2>Fahrzeug-Einstellungen</h2><p className="muted">Nur Werte anzeigen/ändern, die das erkannte Modell und dessen Firmware sicher unterstützen.</p><div className="setting"><span>Fahrmodus</span><select><option>Drive</option><option>Sport</option><option>Eco</option></select></div><div className="setting"><span>Licht</span><button className="toggle">AN / AUS</button></div></section>}
 {tab==='firmware'&&<section className="panel"><h2>Firmware Flash</h2><div className="warning"><b>⚠ Kein Fake-Flash</b><br/>Ein Firmware-Flash darf nur mit einer nachweislich passenden Datei und einem verifizierten Bootloader-Protokoll erfolgen. Ein falsches Image kann den Scooter unbrauchbar machen.</div><label className="drop">{file?file.name:'Firmware-Datei auswählen'}<input type="file" accept=".bin,.hex,.zip" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="flash" disabled={busy||!file||!info?.connected} onClick={flash}>{busy?'Prüfe…':'Kompatibilität prüfen & Flash starten'}</button><div className="progress"><span style={{width:progress+'%'}}/></div><p className="muted">{progress}% — Der aktuelle Build implementiert den echten BLE-Transport, aber keinen erfundenen DFU-Schreibvorgang.</p></section>}
 {tab==='logs'&&<section className="panel log"><h2>Protokoll</h2>{log.length?log.map((x,i)=><div key={i}>{x}</div>):<span className="muted">Noch keine Ereignisse.</span>}</section>}
 <footer>HTTPS erforderlich · Web Bluetooth funktioniert am zuverlässigsten mit Chrome/Edge auf Desktop. iOS unterstützt generisches Web Bluetooth nicht zuverlässig.</footer></main>}
function Card({title,value,suffix}:{title:string,value:string,suffix:string}){return <div className="card"><span>{title}</span><strong>{value}<small>{suffix}</small></strong></div>}
